### ISSUE TITLE
get the account related data

### ISSUE THREAD

**Issue by satendra-dhillon** [JCBarry/argyle#6]
When I complete the authentication process, I received "authenticity_token, institution, public_token" as parameter.

But as I try to make the API call to get the data, all have the username and password required. 
Can you please give me the idea to get the accounts data?

**Comment by JCBarry** [comment]
Which data are you looking for?  The API calls that require username and password are considered Plaid products (such as Auth, Connect or Info).  In the Argyle callback, we've already exchanged the `public_token` for an `access_token` allowing you make further requests for data.

By configuring Argyle with the correct product, you can simply access the `plaid_user` in the Argyle callback and see the data associated with that product.

**Comment by JCBarry** [comment]
Let me know if you have any other questions, happy to help out.
Thanks!
